defaultPlacement: end
fieldLayouts:
  f40ce0f5-7fde-4a84-a60f-31947077dbda:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 9c5da68d-014d-4af5-89a1-60c30bb8a5c1
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 88705dff-cd4d-429b-b993-3f81019f3b89
        userCondition: null
handle: blog
name: Blog
siteSettings:
  8457c135-7678-4f24-af19-07d4c35fa6fb: # Demo Headless EN
    hasUrls: true
    template: null
    uriFormat: '{{craft.entries.section(''pages'').type(''blog'').siteId(1).one().uri}}/{slug}'
  ad9fe9dd-b9d1-478a-b2f0-f19e4955638b: # Demo Headless NL
    hasUrls: true
    template: null
    uriFormat: '{{craft.entries.section(''pages'').type(''blog'').siteId(2).one().uri}}/{slug}'
structure:
  maxLevels: null
  uid: 135047d0-1f1f-48e8-881c-7b1df103e829
