fieldLayouts:
  9f251e80-0296-4793-b6c0-b720e82bc525:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 86a02ff2-4034-400f-b410-43e924a4ffcf
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: aea5a1b0-bcff-41a3-ba69-a80d109574a4
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
