dateModified: 1660369443
email:
  fromEmail: info@angelokeirsebilck.be
  fromName: 'AK Craft Headless'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    851a6d57-751a-4d95-a567-43b9142bb629: Common # Common
    ad9fe9dd-b9d1-478a-b2f0-f19e4955638b: 'AK Craft Headless' # AK Craft Headless
    fad3d472-dae9-43a0-9645-52b832a5d382: 'AK Craft Headless' # AK Craft Headless
system:
  edition: pro
  live: true
  name: 'AK Craft Headless'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
