defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Development Preview'
      -
        - urlFormat
        - 'http://localhost:3002/{language|slice(0,2)}/{uri}?preview=true'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8457c135-7678-4f24-af19-07d4c35fa6fb: # Demo Headless EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'blog/{slug}'
  ad9fe9dd-b9d1-478a-b2f0-f19e4955638b: # Demo Headless NL
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'blog/{slug}'
type: channel
